KCN:
- KCNA2B:
  - 1ZSX
  - 7EJ1
  - 7EJ2
  - 7WF3
  - 7WF4  
- KCNA3:
  - 4BGC
- KCNA8:
  - 3BJ4
  - 3HFC
  - 3HFE
  - 4UMO
  - 6MIE
  - 6UZZ
  - 6VOO
  - 6VO1
- KCNA1:
  - 1EXB
- KCNA2:
  - 1DSX
  - 1QDV
  - 1QDW
  - 2A79
  - 2R9R
  - 3LNM
  - 3LUT
  - 4JTA
  - 4JTC
  - 4JTD
  - 5WIE
  - 6EBK
  - 6EBL
  - 6EBM
- KCNA4:
  - 1KN7

SCN:
- SCN5A:
  - 4OVN
  - 6LQA
  - 6UZ0
  - 6UZ3
  - 7DTC
  - 7FBS
  - 7K18
- SCN4A:
  - 6MC9
  - 6MBA
  - 6AGF
- SCNN1A:
  - 6BQN
- SCN1A:
  - 7DTD
- SCN2A:
  - 1BYY
  - 2KAV
  - 2KXW
  - 2M5E
  - 4JPZ
  - 4RLY
  - 6BUT
  - 6J8E
- SCN9A:
  - 5EK0
  - 6J8G
  - 6J8H
  - 6J8I
  - 6N4Q
  - 6N4R